config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image
  has_rich_text :description

  validates :title, presence: true
  validates :goal, presence: true
  validates :description, presence: true

  validates :title, length: { maximum: 80 }

  validates :goal, numericality: { less_than_or_equal_to: 500, greater_than: 0 }

  validates :image,
    attached: true,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 500.kilobytes, message: I18n.t('errors.messages.file_is_too_large', size: 500, unit: 'kb') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :goal, :image, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(resource, attribute)
    return unless error_for?(resource, attribute)

    content_tag(:p, resource.errors[attribute.to_sym].first, class: 'help is-danger')
  end

  def input_class_for(resource, attribute)
    if error_for?(resource, attribute)
      'input is-danger'
    else
      'input'
    end
  end

  def error_for?(resource, attribute)
    resource && resource.errors[attribute.to_sym].any?
  end

  def to_brl(value)
    number_to_currency(value, unit: 'R$ ', precision: 2, separator: ',', delimiter: '.')
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.slim
doctype html

html
  head
    title Catarsinho
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.has-navbar-fixed-top
    nav.navbar.is-fixed-top.is-link role="navigation" aria-label="main navigation"
      .navbar-brand
        = link_to root_path, class: 'navbar-item'
          h5.title.is-5.has-text-white CATARSINHO

      .navbar-menu
        .navbar-end
          .navbar-item
            .buttons
              = link_to 'New Project', new_project_path, class: 'button is-primary'

    .section
      .container.is-fluid
        - if notice
          .notification.is-success = notice
        = yield

app/views/projects/_form.html.slim
= form_with(model: project, local: true, html: { id: 'project-form' }) do |form|
  - if project.errors.any?
    .notification.is-danger Some errors prohibited this project from being saved

  .field
    = form.label :title, class: 'label'
    .control.is-expanded
      = form.text_field :title, class: input_class_for(project, :title)
    = errors_for(project, :title)

  .field
    = form.label :goal, class: 'label'
    .control.is-expanded
      = form.text_field :goal, class: input_class_for(project, :goal)
    = errors_for(project, :goal)

  .field
    = form.label :image, class: 'label'
    .control
      .file.has-name.is-fullwidth
        label.file-label
          = form.file_field :image,
            class: 'file-input',
            accept: 'image/png,image/jpg,image/jpeg'

          span.file-cta
            span.file-icon
              i.fas.fa-upload

            span.file-label
              | Choose a file…

          span#file-name.file-name
    = errors_for(project, :image)

  .field
    = form.label :description, class: 'label'
    .control
      = form.rich_text_area :description
    = errors_for(project, :description)

  .field.is-grouped.is-grouped-right
    .control
      = link_to 'Back', projects_path, class: 'button is-light'
    .control
      = form.submit class: 'button is-primary'

javascript:
  let addFileInputListener = function () {
    let fileInput = document.getElementById('project_image')
    let fileName = document.getElementById('file-name')

    fileInput.onchange = function () {
      if (fileInput.files.length > 0) {
        fileName.innerHTML = fileInput.files[0].name
      }
    }
  }

  let initGoalInput = function () {
    let goalInput = document.getElementById('project_goal')

    goalInput.value = goalInput.value.toString().replace('.', ',')

    let maskOptions = {
      alias: 'currency',
      prefix: 'R$ ',
      radixPoint: ',',
      allowMinus: false,
      rightAlign: false
    }
    new Inputmask(maskOptions).mask(goalInput)

    document.getElementById('project-form').addEventListener('submit', function (event) {
      let unmaskedValue = goalInput.inputmask.unmaskedvalue()
      goalInput.inputmask.remove()
      goalInput.value = parseFloat(unmaskedValue.replace(',', '.'))
    })
  }

  document.addEventListener('DOMContentLoaded', function () {
    addFileInputListener()
    initGoalInput()
  })

app/views/projects/_project_card.html.slim
.card
  = link_to project_path(project), class: 'card-image' do
    figure.image.is-16by9
      = image_tag(project.image, alt: "Project #{project.title} Image")

  .card-content
    = link_to project_path(project), class: 'media' do
      .media-content
        p.title.is-4 = project.title
        p.subtitle.is-6 By you

    .content
      b = to_brl(project.goal)
      b  goal

css:
  .card .content {
    text-align: right;
  }

app/views/projects/edit.html.slim
.columns.is-centered
  .column.is-7
    nav.breadcrumb.has-succeeds-separator aria-label="breadcrumbs"
      ul
        li
          = link_to('Projects', projects_path)
        li.is-active
          a(aria-current="page") Edit Project

    .box
      h5.title.is-5 Project Form

      = render 'form', project: @project

app/views/projects/index.html.slim
h3.title.is-3 My Projects

.notification.is-white
  - if @projects.empty?
    | There's no project created yet. Create a project
  - else
    | Create a new project
  =< link_to 'here', new_project_path
  | .


.columns.is-multiline
  - @projects.each do |project|
    .column.is-4
      = render 'project_card', project: project

app/views/projects/new.html.slim
.columns.is-centered
  .column.is-7
    nav.breadcrumb.has-succeeds-separator aria-label="breadcrumbs"
      ul
        li
          = link_to('Projects', projects_path)
        li.is-active
          a(aria-current="page") New Project

    .box
      h5.title.is-5 Project Form

      = render 'form', project: @project

app/views/projects/show.html.slim
.columns.is-centered
  .column.is-7
    nav.breadcrumb.has-succeeds-separator aria-label="breadcrumbs"
      ul
        li
          = link_to('Projects', projects_path)
        li.is-active
          a(aria-current="page") Project Detail

.columns.is-centered
  .column.is-4
    .box
      h5.title.is-5 = @project.title
      p
        figure.image.is-16by9
          = image_tag(@project.image)

      p
        == @project.description

  .column.is-3
    .box
      h5.title.is-5 Details

      p.has-text-weight-bold	Goal
      span = to_brl(@project.goal)

      p.has-text-weight-bold	Author
      span You

    .box
      h5.title.is-5 Actions

      .field
        = link_to edit_project_path(@project), class: 'button is-primary is-fullwidth' do
          span.icon
            i.fas.fa-edit
          span Edit Project
      .field
        = link_to @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger is-fullwidth' do
          span.icon
            i.fas.fa-trash
          span Destroy Project

      .field
        = link_to projects_path, class: 'button is-light is-fullwidth'
          span.icon
            i.fas.fa-arrow-left
          span Back to Projects